= SAÉ 3.01 2024-2025
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-2

// Tags TODO
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

// TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

WARNING: Ce dépôt présente le projet à développer dans le cadre de la SAÉ 3.01 du BUT2 Informatique de l'IUT de Blagnac.

toc::[]

== Equipe

Projet est réalisé par::
- https://github.com/NicodeH[Nicolas Ho] : Scrum Master
- https://github.com/luca-gchs[Luca Gaches] : Développeur
- https://github.com/summerflamme[Robin Gourgues] : Développeur
- https://github.com/Melllvin[Melvin Bouyssou] : Product Owner


Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB]

== Réalisations 
- Release dernière version : A venir
- https://github.com/orgs/IUT-Blagnac/projects/255/views/1[Lien vers le backlog]

== Projet Site Web

=== Contexte général

Style & Semelle est une entreprise française de chaussures, fondée en 2005 par cinq amis passionnés de mode et d’engagement éthique, qui allie fabrication locale et sélection de marques internationales pour offrir une gamme variée et responsable. Avec des boutiques dans les principales villes françaises et un site e-commerce performant, elle attire une clientèle large, entre amateurs de mode urbaine et consommateurs soucieux de l’impact environnemental. Son engagement pour une mode éthique, grâce à une production artisanale et des matériaux durables, ainsi que sa stratégie marketing axée sur les réseaux sociaux, lui permettent de se distinguer dans un marché en pleine évolution.

Pour consolider sa position face à une concurrence accrue et aux attentes croissantes des clients pour le numérique, Style & Semelle souhaite rénover et optimiser son site e-commerce. L’appel d’offres lancé vise à créer une expérience utilisateur plus fluide, avec des fonctionnalités innovantes comme la personnalisation et un parcours client optimisé, pour fidéliser et attirer davantage de jeunes acheteurs en ligne. Le projet inclut la refonte de son design avec un CFDT (Cahier des Charges Fonctionnel Détaillé) précisant les besoins techniques et les exigences de performance. En renforçant ainsi son offre numérique, Style & Semelle aspire à capter de nouvelles parts de marché tout en affirmant son identité de marque responsable et moderne.

=== Gestion de projet & Qualité
- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-2/blob/master/documentations/doc-conception/doc-concept-v1.adoc[Lien vers la doc conception (tous les diagrammes)]
- https://github.com/orgs/IUT-Blagnac/projects/255/views/1[Lien vers le backlog (issues et user stories)]
- Lien vers le cahier de tests
- Indicateurs de qualité du code (dette technique)
- ...

== Projet IoT

=== Contexte général

Style & Semelle, PME spécialisée dans la conception et la vente de chaussures, est implantée dans plusieurs grandes villes françaises et souhaite élargir son activité en lançant un site e-commerce pour toucher une clientèle plus large et rester compétitive. En parallèle, l’entreprise prévoit d’installer un réseau de capteurs dans ses magasins et entrepôts pour recueillir des données en temps réel, telles que la température, l’humidité, la qualité de l’air et la détection de présence, afin d'améliorer la sécurité et l’efficacité opérationnelle. Ces informations, transmises au serveur toutes les 10 minutes, permettront d’optimiser la gestion et la croissance de l’entreprise dans un marché en pleine expansion.

=== Gestion de projet & Qualité
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Lien vers le cahier de tests
- Indicateurs de qualité du code (dette technique)
- ...

== Évaluations hebdomadaires
Voici un exemple d'évaluation (à remplacer) :

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image"></iframe>
++++
endif::[]

== Historique des journées de télétravail

=== À venir
- ...

=== Passées
- **06/11/2024** : de 9h30 à 12h30
