= SAÉ 3.01 2024-2025
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-2

// Tags TODO
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

// TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

WARNING: Ce dépôt présente le projet à développer dans le cadre de la SAÉ 3.01 du BUT2 Informatique de l'IUT de Blagnac.

toc::[]

== Equipe

Projet est réalisé par::
- https://github.com/NicodeH[Nicolas Ho] : Scrum Master
- https://github.com/luca-gchs[Luca Gaches] : Développeur
- https://github.com/summerflamme[Robin Gourgues] : Développeur
- https://github.com/Melllvin[Melvin Bouyssou] : Product Owner


Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB]

== Réalisations 
- Lien vers la partie site web
- Lien vers la partie base de données
- Lien vers la partie IoT

== Contexte général

La Roue Tourne, PME française de réparation de vélos, est devenue une référence dans son domaine, avec des magasins dans plusieurs grandes villes, dont Toulouse, Paris, Lyon, Agen et Angers. Fondée en 2012 par quatre passionnés, l’entreprise a connu une croissance rapide grâce à l’augmentation de l’usage du vélo, particulièrement lors du confinement et des Jeux Olympiques de 2024, qui ont favorisé les déplacements à vélo. Désireuse de répondre aux nouvelles attentes de mobilité durable, La Roue Tourne souhaite désormais élargir son offre en se diversifiant. En plus de la réparation, elle propose déjà la vente d’accessoires et la location de vélos en magasin.

Pour faire face à une concurrence accrue et toucher une clientèle plus large, l’entreprise envisage de lancer un site e-commerce afin de vendre des vélos neufs et reconditionnés, des accessoires, des équipements, et même des vêtements. Ce site permettra de renforcer sa présence sur le marché et de capter de nouvelles parts de marché, optimisant ainsi son retour sur investissement. La Roue Tourne a donc lancé un appel d’offres pour développer cette plateforme de vente en ligne, un projet stratégique visant à ancrer sa position dans un secteur en pleine expansion, tout en capitalisant sur la montée de l’intérêt pour la mobilité douce.

== Gestion de projet & Qualité
- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-2/blob/master/documentations/doc-conception/doc-concept-v1.adoc[Lien vers la doc conception (tous les diagrammes)]
- https://github.com/orgs/IUT-Blagnac/projects/255/views/1[Lien vers le backlog (issues et user stories)]
- Lien vers le cahier de tests
- Indicateurs de qualité du code (dette technique)
- ...

== Évaluation hebdomadaire
Voici un exemple d'évaluation (à remplacer) :

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image"></iframe>
++++
endif::[]

== Historique des journées de télétravail

=== À venir
- ...

=== Passées
- **06/11/2024** : de 9h30 à 12h30
