services:
    php:
        build: .
        volumes: 
            - ./:/var/www/html
            - /var/log/apache2/app:/var/log/apache2/
        ports:
            - 8080:80
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: SAE301
            MYSQL_USER: G1A2
            MYSQL_PASSWORD: 1234
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - 8081:80
        depends_on:
            - mysql

volumes:
    db_data:
